"""initial relational model

Revision ID: 9245a9db9e2f
Revises: 
Create Date: 2026-08-31 21:18:58.146323
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '9245a9db9e2f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fhir_sync_log',
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('fhir_resource_type', sa.String(length=80), nullable=False),
    sa.Column('fhir_resource_id', sa.String(length=120), nullable=True),
    sa.Column('fhir_version_id', sa.String(length=40), nullable=True),
    sa.Column('sync_status', sa.Enum('PENDING', 'SYNCED', 'ERROR', name='fhir_sync_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('last_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fhir_sync_log')),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_fhir_sync_log_entity_type_entity_id')
    )
    op.create_index(op.f('ix_fhir_sync_log_entity_type'), 'fhir_sync_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_fhir_sync_log_sync_status'), 'fhir_sync_log', ['sync_status'], unique=False)
    op.create_table('organizations',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('organization_type', sa.Enum('EPS', 'IPS', name='organization_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('parent_organization_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('restored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restored_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("(organization_type = 'EPS' AND parent_organization_id IS NULL) OR (organization_type = 'IPS' AND parent_organization_id IS NOT NULL)", name=op.f('ck_organizations_hierarchy')),
    sa.CheckConstraint('parent_organization_id IS NULL OR parent_organization_id <> id', name=op.f('ck_organizations_not_self_parent')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_organizations_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_organizations_deleted_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['parent_organization_id'], ['organizations.id'], name=op.f('fk_organizations_parent_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['restored_by'], ['users.id'], name=op.f('fk_organizations_restored_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_organizations_updated_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('code', name=op.f('uq_organizations_code'))
    )
    op.create_index(op.f('ix_organizations_deleted_at'), 'organizations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_organizations_organization_type'), 'organizations', ['organization_type'], unique=False)
    op.create_index(op.f('ix_organizations_parent_organization_id'), 'organizations', ['parent_organization_id'], unique=False)
    op.create_table('roles',
    sa.Column('code', sa.Enum('ADMIN', 'EPS_COORDINATOR', 'IPS_CLINICAL_OPERATOR', 'PATIENT', name='role_code', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('locations',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('parent_location_id', sa.Uuid(), nullable=True),
    sa.Column('location_type', sa.Enum('FACILITY', 'WARD', 'ROOM', 'BED', name='location_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('service', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'OCCUPIED', 'RESERVED', 'CLEANING', 'BLOCKED', 'MAINTENANCE', name='bed_status', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('restored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restored_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("(location_type = 'BED' AND status IS NOT NULL) OR (location_type <> 'BED' AND status IS NULL)", name=op.f('ck_locations_status_only_for_beds')),
    sa.CheckConstraint('parent_location_id IS NULL OR parent_location_id <> id', name=op.f('ck_locations_not_self_parent')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_locations_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_locations_deleted_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_locations_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_location_id'], ['locations.id'], name=op.f('fk_locations_parent_location_id_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['restored_by'], ['users.id'], name=op.f('fk_locations_restored_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_locations_updated_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations')),
    sa.UniqueConstraint('organization_id', 'code', name='uq_locations_organization_id_code')
    )
    op.create_index(op.f('ix_locations_deleted_at'), 'locations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_locations_location_type'), 'locations', ['location_type'], unique=False)
    op.create_index(op.f('ix_locations_organization_id'), 'locations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_locations_parent_location_id'), 'locations', ['parent_location_id'], unique=False)
    op.create_index(op.f('ix_locations_status'), 'locations', ['status'], unique=False)
    op.create_table('patients',
    sa.Column('document_type', sa.Enum('CC', 'TI', 'CE', 'PA', 'RC', name='document_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('document_number', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'other', 'unknown', name='administrative_gender', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('eps_organization_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('restored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restored_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_patients_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_patients_deleted_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['eps_organization_id'], ['organizations.id'], name=op.f('fk_patients_eps_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['restored_by'], ['users.id'], name=op.f('fk_patients_restored_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_patients_updated_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients')),
    sa.UniqueConstraint('document_type', 'document_number', name='uq_patients_document_type_document_number')
    )
    op.create_index(op.f('ix_patients_deleted_at'), 'patients', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_patients_document_number'), 'patients', ['document_number'], unique=False)
    op.create_index(op.f('ix_patients_eps_organization_id'), 'patients', ['eps_organization_id'], unique=False)
    op.create_table('encounters',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('encounter_class', sa.Enum('IMP', 'AMB', 'EMER', name='encounter_class', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('planned', 'arrived', 'in-progress', 'finished', 'cancelled', name='encounter_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('priority', sa.Enum('ROUTINE', 'URGENT', 'EMERGENCY', name='encounter_priority', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('reason_text', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('restored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restored_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint('ended_at IS NULL OR ended_at >= started_at', name=op.f('ck_encounters_period_order')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_encounters_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_encounters_deleted_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_encounters_location_id_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_encounters_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_encounters_patient_id_patients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['restored_by'], ['users.id'], name=op.f('fk_encounters_restored_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_encounters_updated_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_encounters'))
    )
    op.create_index(op.f('ix_encounters_deleted_at'), 'encounters', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_encounters_location_id'), 'encounters', ['location_id'], unique=False)
    op.create_index(op.f('ix_encounters_organization_id'), 'encounters', ['organization_id'], unique=False)
    op.create_index(op.f('ix_encounters_patient_id'), 'encounters', ['patient_id'], unique=False)
    op.create_index(op.f('ix_encounters_status'), 'encounters', ['status'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_users_patient_id_patients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_patient_id'), 'users', ['patient_id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_log',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.Enum('LOGIN', 'CREATE', 'SOFT_EDIT', 'SOFT_DELETE', 'RESTORE', 'FHIR_SYNC', name='audit_action', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_log_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('bed_requests',
    sa.Column('encounter_id', sa.Uuid(), nullable=False),
    sa.Column('requesting_organization_id', sa.Uuid(), nullable=False),
    sa.Column('target_organization_id', sa.Uuid(), nullable=True),
    sa.Column('required_service', sa.String(length=120), nullable=False),
    sa.Column('priority', sa.Enum('ROUTINE', 'URGENT', 'EMERGENCY', name='bed_request_priority', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_REVIEW', 'ASSIGNED', 'REJECTED', 'CANCELLED', name='bed_request_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('restored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restored_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_bed_requests_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_bed_requests_deleted_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], name=op.f('fk_bed_requests_encounter_id_encounters'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requesting_organization_id'], ['organizations.id'], name=op.f('fk_bed_requests_requesting_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['restored_by'], ['users.id'], name=op.f('fk_bed_requests_restored_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['target_organization_id'], ['organizations.id'], name=op.f('fk_bed_requests_target_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_bed_requests_updated_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bed_requests'))
    )
    op.create_index(op.f('ix_bed_requests_deleted_at'), 'bed_requests', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_bed_requests_encounter_id'), 'bed_requests', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_bed_requests_requesting_organization_id'), 'bed_requests', ['requesting_organization_id'], unique=False)
    op.create_index(op.f('ix_bed_requests_status'), 'bed_requests', ['status'], unique=False)
    op.create_index(op.f('ix_bed_requests_target_organization_id'), 'bed_requests', ['target_organization_id'], unique=False)
    op.create_table('bed_status_events',
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('encounter_id', sa.Uuid(), nullable=True),
    sa.Column('previous_status', sa.Enum('AVAILABLE', 'OCCUPIED', 'RESERVED', 'CLEANING', 'BLOCKED', 'MAINTENANCE', name='bed_event_previous_status', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('new_status', sa.Enum('AVAILABLE', 'OCCUPIED', 'RESERVED', 'CLEANING', 'BLOCKED', 'MAINTENANCE', name='bed_event_new_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('event_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('fk_bed_status_events_changed_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], name=op.f('fk_bed_status_events_encounter_id_encounters'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_bed_status_events_location_id_locations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bed_status_events'))
    )
    op.create_index(op.f('ix_bed_status_events_encounter_id'), 'bed_status_events', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_bed_status_events_event_at'), 'bed_status_events', ['event_at'], unique=False)
    op.create_index(op.f('ix_bed_status_events_location_id'), 'bed_status_events', ['location_id'], unique=False)
    op.create_table('observations',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('encounter_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('registered', 'preliminary', 'final', 'amended', 'cancelled', name='observation_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('code_system', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('display', sa.String(length=200), nullable=False),
    sa.Column('value_numeric', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('value_text', sa.String(length=500), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('unit_system', sa.String(length=200), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('restored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restored_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint('value_numeric IS NOT NULL OR value_text IS NOT NULL', name=op.f('ck_observations_has_value')),
    sa.CheckConstraint('value_numeric IS NULL OR unit IS NOT NULL', name=op.f('ck_observations_numeric_needs_unit')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_observations_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_observations_deleted_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], name=op.f('fk_observations_encounter_id_encounters'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_observations_patient_id_patients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['restored_by'], ['users.id'], name=op.f('fk_observations_restored_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_observations_updated_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observations'))
    )
    op.create_index(op.f('ix_observations_code'), 'observations', ['code'], unique=False)
    op.create_index(op.f('ix_observations_deleted_at'), 'observations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_observations_encounter_id'), 'observations', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_observations_observed_at'), 'observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_observations_patient_id'), 'observations', ['patient_id'], unique=False)
    op.create_table('record_versions',
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('fk_record_versions_changed_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_record_versions')),
    sa.UniqueConstraint('entity_type', 'entity_id', 'version_number', name='uq_record_versions_entity_type_entity_id_version_number')
    )
    op.create_index(op.f('ix_record_versions_entity_id'), 'record_versions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_record_versions_entity_type'), 'record_versions', ['entity_type'], unique=False)
    op.create_table('bed_assignments',
    sa.Column('bed_request_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RELEASED', 'CANCELLED', name='bed_assignment_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('restored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restored_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint('released_at IS NULL OR released_at >= assigned_at', name=op.f('ck_bed_assignments_period_order')),
    sa.ForeignKeyConstraint(['bed_request_id'], ['bed_requests.id'], name=op.f('fk_bed_assignments_bed_request_id_bed_requests'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_bed_assignments_created_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_bed_assignments_deleted_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_bed_assignments_location_id_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['restored_by'], ['users.id'], name=op.f('fk_bed_assignments_restored_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_bed_assignments_updated_by_users'), ondelete='RESTRICT', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bed_assignments'))
    )
    op.create_index(op.f('ix_bed_assignments_bed_request_id'), 'bed_assignments', ['bed_request_id'], unique=False)
    op.create_index(op.f('ix_bed_assignments_deleted_at'), 'bed_assignments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_bed_assignments_location_id'), 'bed_assignments', ['location_id'], unique=False)
    op.create_index('uq_bed_assignments_one_active_per_bed', 'bed_assignments', ['location_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE' AND deleted_at IS NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_bed_assignments_one_active_per_bed', table_name='bed_assignments', postgresql_where=sa.text("status = 'ACTIVE' AND deleted_at IS NULL"))
    op.drop_index(op.f('ix_bed_assignments_location_id'), table_name='bed_assignments')
    op.drop_index(op.f('ix_bed_assignments_deleted_at'), table_name='bed_assignments')
    op.drop_index(op.f('ix_bed_assignments_bed_request_id'), table_name='bed_assignments')
    op.drop_table('bed_assignments')
    op.drop_index(op.f('ix_record_versions_entity_type'), table_name='record_versions')
    op.drop_index(op.f('ix_record_versions_entity_id'), table_name='record_versions')
    op.drop_table('record_versions')
    op.drop_index(op.f('ix_observations_patient_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_observed_at'), table_name='observations')
    op.drop_index(op.f('ix_observations_encounter_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_deleted_at'), table_name='observations')
    op.drop_index(op.f('ix_observations_code'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_bed_status_events_location_id'), table_name='bed_status_events')
    op.drop_index(op.f('ix_bed_status_events_event_at'), table_name='bed_status_events')
    op.drop_index(op.f('ix_bed_status_events_encounter_id'), table_name='bed_status_events')
    op.drop_table('bed_status_events')
    op.drop_index(op.f('ix_bed_requests_target_organization_id'), table_name='bed_requests')
    op.drop_index(op.f('ix_bed_requests_status'), table_name='bed_requests')
    op.drop_index(op.f('ix_bed_requests_requesting_organization_id'), table_name='bed_requests')
    op.drop_index(op.f('ix_bed_requests_encounter_id'), table_name='bed_requests')
    op.drop_index(op.f('ix_bed_requests_deleted_at'), table_name='bed_requests')
    op.drop_table('bed_requests')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_patient_id'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_encounters_status'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_patient_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_organization_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_location_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_deleted_at'), table_name='encounters')
    op.drop_table('encounters')
    op.drop_index(op.f('ix_patients_eps_organization_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_document_number'), table_name='patients')
    op.drop_index(op.f('ix_patients_deleted_at'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_locations_status'), table_name='locations')
    op.drop_index(op.f('ix_locations_parent_location_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_organization_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_location_type'), table_name='locations')
    op.drop_index(op.f('ix_locations_deleted_at'), table_name='locations')
    op.drop_table('locations')
    op.drop_table('roles')
    op.drop_index(op.f('ix_organizations_parent_organization_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_organization_type'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_deleted_at'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_fhir_sync_log_sync_status'), table_name='fhir_sync_log')
    op.drop_index(op.f('ix_fhir_sync_log_entity_type'), table_name='fhir_sync_log')
    op.drop_table('fhir_sync_log')
    # ### end Alembic commands ###
