"""LOINC codes used by the seed and by observation validation.

Every code here was taken from loinc.org and matches the FHIR vital-signs
profile. Codes are never invented: an observation whose measurement is not in
this table must have its code looked up and added deliberately.

Units follow UCUM (http://unitsofmeasure.org).
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class LoincCode:
    code: str
    display: str
    unit: str
    low: float
    high: float
    """``low``/``high`` bound the synthetic values generated by the seed so the
    demo data stays clinically plausible."""


HEART_RATE = LoincCode("8867-4", "Heart rate", "/min", 55, 115)
RESPIRATORY_RATE = LoincCode("9279-1", "Respiratory rate", "/min", 12, 26)
BODY_TEMPERATURE = LoincCode("8310-5", "Body temperature", "Cel", 36.0, 39.2)
SYSTOLIC_BP = LoincCode("8480-6", "Systolic blood pressure", "mm[Hg]", 95, 165)
DIASTOLIC_BP = LoincCode("8462-4", "Diastolic blood pressure", "mm[Hg]", 55, 100)
OXYGEN_SATURATION = LoincCode(
    "59408-5", "Oxygen saturation in Arterial blood by Pulse oximetry", "%", 88, 100
)

VITAL_SIGNS: tuple[LoincCode, ...] = (
    HEART_RATE,
    RESPIRATORY_RATE,
    BODY_TEMPERATURE,
    SYSTOLIC_BP,
    DIASTOLIC_BP,
    OXYGEN_SATURATION,
)

BY_CODE: dict[str, LoincCode] = {item.code: item for item in VITAL_SIGNS}
